name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: |
          echo "VERSION=$(git tag --sort=-v:refname | head -n 1 | sed 's/^v//')" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Automated release based on git tags.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
